server:
  port: 8087
  servlet:
    context-path: /autoMail

spring:
  profiles:
    active: local
  project:
    name: garry
    main:
      allow-bean-definition-overriding: true
  application:
    name: autoMail
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3308/mailService?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull"
    username: root
    password: "root"
    druid:
      max-active: 100
      initialSize: 5
      minIdle: 5
  mail:
    host: smtp.163.com
    username: 18676391882@163.com
    password: JMJCBTQZWGMMIBAJ
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enabled: true
            required: true
  liquibase:
     # 不配置默认会查找'classpath:/db/changelog/db.changelog-master.yaml'文件
     change-log: 'classpath:/db/changelog/db.changelog-master.yml'
  jpa:
    show-sql: false
    hibernate:
    ddl-auto: none
mybatis:
  mapper-locations: classpath*:com/garry/mail/dao/*.xml
  type-aliases-package: com.garry.mail.dao

sender: 18676391882@163.com