server:
  port: 8087
  servlet:
    context-path: /autoMail

spring:
  profiles:
    active: local
  project:
    name: garry
    main:
      allow-bean-definition-overriding: true
  application:
    name: autoMail
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3308/mailService?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull"
    username: root
    password: "root"
    druid:
      max-active: 100
      initialSize: 5
      minIdle: 5
  mail:
    host: smtp.163.com
    username: garry_xian92@163.com
    password: YKVSDUYLUYUNFWYG
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enabled: true
            required: true
